import styles from "../styles/Home.module.css";
import Head from "next/head";
import * as React from "react";

const Layout = ({ children, title }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{'Cope Notes' | title}</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
        <meta name="viewport" content="initial-scale=1, width=device-width"/>
      </Head>

      <main className={styles.main}>
        {children}
      </main>
    </div>
  )
}

export default Layout