version: '3'
services:
  api:
    container_name: copenotes-api
    restart: always
    build:
      dockerfile: Dockerfile.local
      context: ./
    ports:
      - '8001:8001'
    volumes:
      - ./:/usr/src/app
